#!D:\NCKH\Workspace\2025\DOING\SkinCancer_HAM1000_FineTuning_MobileNet\repo\env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
